# Generated by Django 5.2.7 on 2025-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RejectList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('GROUP', models.CharField(blank=True, max_length=100, null=True)),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PROPOSAL_DATE', models.DateField(blank=True, null=True)),
                ('YEAR', models.IntegerField(blank=True, null=True)),
                ('MONTH', models.CharField(blank=True, max_length=50, null=True)),
                ('LOCATION', models.CharField(blank=True, max_length=100, null=True)),
                ('FOLLOW', models.CharField(blank=True, max_length=100, null=True)),
                ('PROPRIETOR', models.CharField(blank=True, max_length=100, null=True)),
                ('MEDIATOR', models.CharField(blank=True, max_length=100, null=True)),
                ('CONTACT_NO', models.CharField(blank=True, max_length=20, null=True)),
                ('FILE_SEEN', models.CharField(blank=True, max_length=10, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=50, null=True)),
                ('REASON', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reject_client_details',
                'managed': False,
            },
        ),
    ]
